### ISSUE TITLE
Question about AttackShortcutKey 

### ISSUE THREAD

**Issue by Chololoco13** [Masuzu/GBFCombatSniffer#6]
AttackShortcutKey: this option is amazing but I was wondering if you can abuse this option. I have a question.
Question: I use this option with only one window, I press hundreds of times even when I get the window "Processing Waiting for last turn will be processed" I do not press "Ok" and I continue pressing AttackShortcutKey.
There is no risk of ban for that? or do I need to press "Ok"?
![chrome_aJyw2axTi2](https://user-images.githubusercontent.com/25869534/55687988-1d3c2680-5939-11e9-9a73-c9130e0fe6b1.png)

about using the page http://granblue-raidfinder.herokuapp.com/. Can only use this page? 
Personally I did not use that page because it was annoying that people published their raid many times. 
![chrome_HJPsZvNFpK](https://user-images.githubusercontent.com/25869534/55687961-c20a3400-5938-11e9-8cd0-e84fdcc4e013.png)

Google translator-

**Comment by Masuzu** [comment]
Hello,

Thank you for the feedback. What the computer sees is not what the user actually does and sees. I will add a configurable delay between each "key press" for a shortcut key (as you can still maintain the attack shortcut key pressed until the attack goes through for now), and an option to automatically close the "Processing turn" popup message.

As for raid joining you can use **any** raid finder tool you prefer, as long as you copy the code to your clipboard, pressing the raid joining shortcut will try and join that raid.
(I will also add more messages in the console to indicate why a raid failed to be joined when it happens).

**Comment by Masuzu** [comment]
More customization related to your remarks were provided in v1.6.0 https://gbtools.azurewebsites.net/CombatSniffer/en/Home/PatchNotes#1-6-0, as well as the very useful  error popup window automatic dismissal.
