### ISSUE TITLE
Party Names not showing properly / How to refresh battle only, not the entire page

### ISSUE THREAD

**Issue by lz83** [Masuzu/GBFCombatSniffer#7]
The names show as XXX instead of displaying my character name or any of the names in the party

![image](https://user-images.githubusercontent.com/22550901/56085170-a947c580-5df3-11e9-9afb-571124c03f08.png)

Secondary question: what key is used to refresh the battle but not the entire page as shown in the Bahamut HL MVP Racing video? I checked the ini file but did not find a binding to refresh the battle but not the page. 

Thank you!

**Comment by lz83** [comment]
Also, is there a shortcut key to use summons?

**Comment by Masuzu** [comment]
@lz83 Summon shortcuts are available.

Fast refresh is performed by navigating back then navigating forward (some mouses have buttons on the side to perform that). However, note that doing so will sometimes result in the buttons being stuck, which requires a hard reload of the page in that case (F5).

I took note of the request.

**Comment by lz83** [comment]
Thanks!
